# Generated by Django 3.2 on 2022-08-01 14:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='firstname')),
                ('lastname', models.CharField(blank=True, max_length=255, verbose_name='lastname')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dictionary.comment', verbose_name='reply_to')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('verb', 'Verb'), ('noun', 'Noun'), ('adjective', 'Adjective'), ('pronoun', 'Pronoun'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection')], max_length=12, verbose_name='type')),
                ('antonyms', models.ManyToManyField(blank=True, related_name='_dictionary_entry_antonyms_+', to='dictionary.Entry', verbose_name='antonyms')),
                ('synonyms', models.ManyToManyField(blank=True, related_name='_dictionary_entry_synonyms_+', to='dictionary.Entry', verbose_name='synonyms')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='word')),
                ('firstname', models.CharField(max_length=255, verbose_name='firstname')),
                ('lastname', models.CharField(blank=True, max_length=255, verbose_name='lastname')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('social_media_id', models.CharField(blank=True, max_length=300, verbose_name='social_media_id')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Suggest',
                'verbose_name_plural': 'Suggests',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='word')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Farsi')], max_length=2, verbose_name='language')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='dictionary.entry', verbose_name='entry')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='Images/', verbose_name='file')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dictionary.entry', verbose_name='entry')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='dictionary.entry', verbose_name='entry')),
            ],
            options={
                'verbose_name': 'Example',
                'verbose_name_plural': 'Examples',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='translation',
            field=models.ManyToManyField(blank=True, limit_choices_to={'language': 'fa'}, related_name='translates', to='dictionary.Word', verbose_name='translation'),
        ),
        migrations.AddField(
            model_name='entry',
            name='word',
            field=models.ForeignKey(limit_choices_to={'language': 'en'}, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='dictionary.word', verbose_name='word'),
        ),
        migrations.CreateModel(
            name='CommentsFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('L', 'Like'), ('D', 'Dislike')], max_length=1, verbose_name='type')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='dictionary.comment', verbose_name='comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Comments Feedback',
                'verbose_name_plural': 'Comments Feedbacks',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='word',
            field=models.ForeignKey(limit_choices_to={'language': 'en'}, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dictionary.word', verbose_name='word'),
        ),
    ]
