# Generated by Django 3.2 on 2022-08-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20220802_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsfeedback',
            name='user',
        ),
        migrations.AlterField(
            model_name='suggest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='suggest',
            name='social_media_id',
            field=models.CharField(blank=True, max_length=500, verbose_name='social_media_id'),
        ),
    ]
