# Generated by Django 3.2 on 2022-08-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20220803_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='commentsfeedback',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='dictionary.comment', verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='commentsfeedback',
            name='user_ip',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='dictionary.ipmodel', verbose_name='user_ip'),
            preserve_default=False,
        ),
    ]
